## Car Price Prediction model

This project aims to develop a predictive model for estimating car prices based on various features such as brand, model, year of manufacture, mileage, engine capacity, and fuel type. By applying data science and machine learning techniques, the project seeks to analyze patterns within historical car sales data. The resulting model will help users, buyers, and sellers make informed decisions by providing accurate and data-driven price predictions.

In [1]:
### importing libraries
import pandas as pd
import numpy as np

In [2]:
### importing dataset
df=pd.read_csv(r"D:\DMP\Kigea Projects\March2026Projects\car-price-prediction\dataset\cardataset.csv")
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [3]:
df.shape

(6019, 13)

In [4]:
df.describe()

              Year  Kilometers_Driven        Seats   New_Price        Price
count  6019.000000       6.019000e+03  5977.000000  824.000000  6019.000000
mean   2013.358199       5.873838e+04     5.278735   20.320716     9.479468
std       3.269742       9.126884e+04     0.808840   20.198119    11.187917
min    1998.000000       1.710000e+02     0.000000    1.000000     0.440000
25%    2011.000000       3.400000e+04     5.000000    7.845000     3.500000
50%    2014.000000       5.300000e+04     5.000000   11.415000     5.640000
75%    2016.000000       7.300000e+04     5.000000   24.010000     9.950000
max    2019.000000       6.500000e+06    10.000000   99.920000   160.000000

In [5]:
df.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price            float64
Price                float64
dtype: object

### Data cleaning

In [6]:
df.head(3)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61,4.50

In [7]:
### Strip Units & Convert to Numeric
def cleanunits(df):
    df["Mileage"]=df["Mileage"].str.split(" ").str[0].astype(float)
    df["Engine"]=df["Engine"].str.split(" ").str[0].astype(float)
    df["Power"] = df["Power"].str.split(" ").str[0]
    df["Power"] = pd.to_numeric(df["Power"], errors="coerce")
    return df
df=cleanunits(df)

In [8]:
print(df.isnull().sum())

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                 143
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [9]:
def clean_data(df):
    df.drop("New_Price", axis=1)
    df["Mileage"].fillna(df["Mileage"].median())
    df["Engine"].fillna(df["Engine"].median())
    df["Power"].fillna(df["Power"].median())
    df["Seats"].fillna(df["Seats"].median())
    return df
df=clean_data(df)

print(df.isnull().sum())

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                 143
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [10]:
df['Brand']=df['Name'].str.split(" ").str[0]
df.drop("Name", axis=1, inplace=True)

In [11]:
df.head()
df.to_csv(r"D:\DMP\Kigea Projects\March2026Projects\car-price-prediction\dataset\cleaned_car_dataset.csv", index=False)

In [12]:
### One-Hot Encoding
df=pd.get_dummies(df, columns=["Fuel_Type","Brand","Owner_Type","Location","Transmission"], drop_first=True)
df.head()

,Year,Kilometers_Driven,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Diesel,Fuel_Type_Electric,...,Location_Chennai,Location_Coimbatore,Location_Delhi,Location_Hyderabad,Location_Jaipur,Location_Kochi,Location_Kolkata,Location_Mumbai,Location_Pune,Transmission_Manual
0,2010,72000,26.60,998.0,58.16,5.0,NaN,1.75,False,False,...,False,False,False,False,False,False,False,True,False,True
1,2015,41000,19.67,1582.0,126.20,5.0,NaN,12.50,True,False,...,False,False,False,False,False,False,False,False,True,True
2,2011,46000,18.20,1199.0,88.70,5.0,8.61,4.50,False,False,...,True,False,False,False,False,False,False,False,False,True
3,2012,87000,20.77,1248.0,88.76,7.0,NaN,6.00,True,False,...,True,False,False,False,False,False,False,False,False,True
4,2013,40670,15.20,1968.0,140.80,5.0,NaN,17.74,True,False,...,False,True,False,False,False,False,False,False,False,False